### ISSUE TITLE
RVDic

### ISSUE THREAD

**Issue by aligol20** [sirraminyavari/RaaiVanUI#45]
سلام
لطفا بنده را راهنمایی کنید که عبارات زیر را در RVDic پیدا کنم
و یا اگر نیستند لطفا آن ها را اضافه کنید:

1. ایجاد حساب کاربری جدید
2. !حساب کاربری دارم
3. لطفاً کد تایید حساب خود را، که به شماره موبایل بالا ارسال شده، در کادر زیر وارد نمایید
4. با ثبت ایمیل در کلیک مایند، شما می‌پذیرید که قوانین کلیک‌مایند .را خوانده و به آن متعهد هستید
5. در صورتی که این ایمیل یا شماره موبایل در کلیک‌مایند ثبت شده باشد، کد تایید تغییر رمزعبور برای شما ارسال خواهد شد
6. حداقل ۸ کارکتر (PasswordPolicyMinLength) 
7. لطفاً کد رمز دوم حساب خود را، که به آدرس ایمیل بالا .ارسال شده، در کادر زیر وارد نمایید

**Comment by sirraminyavari** [comment]
RVDic.SignUp => ایجاد حساب کاربری
RVDic.AlreadyHaveAnAccount => حساب کاربری دارم
RVDic.PasswordPolicyMinLength.replace("n", lnt) => حداقل n کاراکتر
RVDic.Checks.YouMustAgreeWithTermsAndConditions.replace("[n]", Base64.decode(RVGlobal.SystemName)).replace("[m]", Base64.decode(RVGlobal.SystemName)) => با ثبت نامه در کلیک مایند، شما می پذیرید که ...
RVDic.Checks.PleaseEnterTheVerificationCode => لطفا کد تایید را وارد کنید
# موارد 3 و 7 یکی هستن، نیازی نیست که داستان بنویسیم، من یه مقدار خلاصه ترش کردم
# مورد 5 رو کجا استفاده کردی؟ به نظرم پیام بی موردیه

**Comment by sirraminyavari** [comment]
علی این سیاست های مربوط به رمز رو باید از سرور بگیری ها؛ چیز ثابتی نیست

**Comment by aligol20** [comment]
مورد ۵ در دیزاین امیرحسین

![Screen Shot 2021-03-09 at 7 33 25 AM](https://user-images.githubusercontent.com/8493249/110416941-d9fd0c00-80a9-11eb-80ca-7c05b5030baa.png)
مورد ۴ به این شکل نمایش داده میشه
<img width="203" alt="Screen Shot 2021-03-09 at 7 32 25 AM" src="https://user-images.githubusercontent.com/8493249/110416942-d9fd0c00-80a9-11eb-8a20-10bde01af23b.png">
و باید به این شکل باشه
<img width="210" alt="Screen Shot 2021-03-09 at 7 32 48 AM" src="https://user-images.githubusercontent.com/8493249/110416949-de292980-80a9-11eb-8788-0ac25d980bad.png">

**Comment by sirraminyavari** [comment]
این مورد اگر برطرف شده لطفا تیکت رو حذف کن و اگر هم برطرف نشده بگو که چه کمکی می تونم بکنم؟

**Comment by aligol20** [comment]
مشکلات اصلی تقریبا حل شده اند
عباراتی که امیرحسین در طراحی قرار داده با عباراتی که در حال حاضر داریم صد در صد یکی نیستند، همان مفهوم را میرسانند اما عبارات دقیقا یکی نیستند

**Comment by aligol20** [comment]
متن قوانین کلیک مایند نیز صحیح نمایش داده نمیشود
decode(RVGlobal.SystemName)
وقتی از متد فوق استفاده میکنم
این عبارت نمایش داده میشود
<img width="381" alt="Screen Shot 2021-03-27 at 1 09 48 PM" src="https://user-images.githubusercontent.com/8493249/112715419-b6d1b980-8efd-11eb-95e9-b33e1ebd5fbf.png">
