### ISSUE TITLE
دکمه ایجاد حساب کاربری

### ISSUE THREAD

**Issue by Rasoul678** [sirraminyavari/RaaiVanUI#51]
سلام
دکمه ایجاد حساب کاربری کار نمیکنه
اما اگر تو مرورگر تایپ بشه کار میکنه
چون ساختار لاگین تغییر کرده
namespace: /auth/...
تا جایی که تونستم تغییرات رو اعمال کردم
اگر جایی مثلا میره به 
/resetpassword
باید بشه
/auth/resetpassword

**Comment by aligol20** [comment]
fixed
