### ISSUE TITLE
sign up verification

### ISSUE THREAD

**Issue by aligol20** [sirraminyavari/RaaiVanUI#62]
- [x] اینپوت کد تایید ارتفاعش زیاد. باید مثل بقیه اینپوتها باشه
- [x] تایمر سایزش بزرگه یه مقدار . فارسی هم باید باشه
- [x] سایز متن ایمیل بزرگه یه مقدار
- [x] عنوان کد تایید را وارد نمایید هم بزرگه، هم اینکه رنگ و خود متن متفاوته با طراحی
- [x] فاصله ورود به سامانه با بالای کادر یه مقدار کمتره نسبت به بقیه صفحات

**Comment by aligol20** [comment]
@sirraminyavari  
متنی که امیرحسین برای دکمه مرحله اخر ثبت نام در نظر گرفته این هستش 
![Screen Shot 2021-03-27 at 1 25 06 PM](https://user-images.githubusercontent.com/8493249/112715753-d9fd6880-8eff-11eb-93f4-2edd20b33766.png)
درحال حاضر این متن این هستش 
<img width="381" alt="Screen Shot 2021-03-27 at 1 25 21 PM" src="https://user-images.githubusercontent.com/8493249/112715759-e2ee3a00-8eff-11eb-8fa6-a08acc0b2703.png">

**Comment by aligol20** [comment]
@sirraminyavari 
همچنین این عبارت
![Screen Shot 2021-03-27 at 1 26 23 PM](https://user-images.githubusercontent.com/8493249/112715786-07e2ad00-8f00-11eb-9285-72a47eb2a15d.png)
در حال حاضر این هستش 
<img width="330" alt="Screen Shot 2021-03-27 at 1 26 40 PM" src="https://user-images.githubusercontent.com/8493249/112715793-116c1500-8f00-11eb-8610-b46e87bbccf5.png">

**Comment by sirraminyavari** [comment]
آخری رو بذار همین "لطفا کد تایید را وارد نمایید" باشه. متن امیرحسین خیلی بی جهت طولانیه

**Comment by sirraminyavari** [comment]
اون مورد ثبت نام رو هم من توی دیکشنری درست می کنم تو فقط از این استفاده کن:
RVDic.SignUp
