### ISSUE TITLE
general login ui issues

### ISSUE THREAD

**Issue by aligol20** [sirraminyavari/RaaiVanUI#63]
- [x] دکمه تا وقتی که اطلاعات وارد نشده باید غیرفعال بمونه
- [x] علاوه بر ایمیل، شماره موبایل هم باید باشه توی اینپوتها
- [x] عد یه موردی هست که من توی ایکس دی نمیتونم هندل کنم، اینکه فاصله بین اینپوتها رو من برای نمایش ارورها زیاد گذاشتم، شما میتونید فاصله رو کم کنید، در حد نصف چیزی که الان هست، و فقط موقع ارور اون فاصله رو ایجاد کنید برای نمایش پیغام خطا

**Comment by sirraminyavari** [comment]
برای غیرفعال بودن دکمه ها حواست باشه که کامپوننت Button یه prop به اسم disable هم داره و باید از همون استفاده کنی

**Comment by aligol20** [comment]
در مورد ایشیو سوم که میگه برای نمایش اینپوت ها فاصله ایجاد بشه هم لطفا نظرتون رو بگید
@sirraminyavari

**Comment by aligol20** [comment]
در مورد ایشیو دوم هم گفته که علاوه بر ایمیل شماره موبایل رو هم اضافه کنید
لطفا این مورد رو توی ار وی دیک به من بگید
@sirraminyavari

**Comment by sirraminyavari** [comment]
در مورد ایشو دوم، چون فعلا شماره تلفن کار نمی کنه، بذار همون یوزنیم و ایمیل باشه؛ بعد از اینکه شماره تلفن رو هم درست کردیم، اضافش می کنیم. کار خاصی که نداره فقط یه لیبله

**Comment by sirraminyavari** [comment]
در مورد ایشو سوم، هرچقدر که جا داره خودت فاصله رو کم کن. من همیشه فاصله ها رو یک رم میذارم.
فقط  هر کاری که می کنی، فاصله همه جا یکسان باشه. مثلا اگر چند تا اینپوت و دکمه هستن، فاصله بین همشون مساوی باشه

**Comment by aligol20** [comment]
<img width="515" alt="Screen Shot 2021-03-31 at 6 21 03 AM" src="https://user-images.githubusercontent.com/8493249/113078931-5090b380-91e9-11eb-9e91-92d679542cb3.png">
 ایشیو سوم
