### ISSUE TITLE
Sign in UI review

### ISSUE THREAD

**Issue by aligol20** [sirraminyavari/RaaiVanUI#68]
<img width="612" alt="Screen Shot 2021-04-01 at 6 29 09 PM" src="https://user-images.githubusercontent.com/8493249/113305327-27bb0c00-9318-11eb-890c-70d04f5b201a.png">
سلام امیرحسین جان
لطفا  مجددا نگاه کن و اگر ایرادی بود همین جا برام کامنت بذار
<img width="1280" alt="Screen Shot 2021-04-01 at 6 04 19 PM" src="https://user-images.githubusercontent.com/8493249/113302327-2c31f580-9315-11eb-8bc1-a3796b9f2c49.png">

**Comment by ahs1375** [comment]
- [ ] برای حالت ارور در صورت امکان فقط بردر اینپوت قرمز بشه و داخلش همون سفید بمونه. چون لیبلش هم سفید هست بهم نمیان
- [ ] برای حالت ارور بردر قرمز بشه و یک مقدار ضخیم تر. مثلا از 0.5 پیکسل به 1 پیکسل تغییر کنه
- [ ] متن ارور که نام کاربری یا پسورد اشتباهه بهتره که فقط زیر رمز عبور نوشته بشه ولی بردر هردو اینپوت قرمز بشه.
- [ ] رنگ عنوان صفحه هم با کد رنگ #BAC9DC باشه.
- [ ] عنوان دکمه ثبت نام بشه ایجاد حساب کاربری جدید
- [ ] سایز فونت دکمه‌ها یکسان نیست.

**Comment by sirraminyavari** [comment]
من رنگ پیش زمینه اینپوت توی حالت ارور و همچنین ضخامت بوردر رو درست کردم.
@ahs1375 واسه مورد چهارم که کد رنگ گفتی، بهم بگو که توی دیزاین سیستم این میشه کدوم رنگ. چون ما از کد رنگ استفاده نمی کنیم و رنگ ها باید اسم داشته باشن.

**Comment by sirraminyavari** [comment]
@ahs1375 کد رنگ رو پیدا کردم من اسمشو گذاشتم: distant

**Comment by aligol20** [comment]
<img width="582" alt="Screen Shot 2021-04-03 at 3 48 17 PM" src="https://user-images.githubusercontent.com/8493249/113476956-04b56700-9494-11eb-9c1b-ce8a32fcca39.png">
<img width="538" alt="Screen Shot 2021-04-03 at 3 48 36 PM" src="https://user-images.githubusercontent.com/8493249/113476961-0ed76580-9494-11eb-986a-a923d1c4610f.png">
@ahs1375 
امیرحسین جان لطفا مجدد بررسی کن
اگر مشکلی نداشت ایشیو رو ببند

**Comment by ahs1375** [comment]
- [ ] خیلی عالی . فقط یه موردی که فراموش کردم بگم، اینکه علاوه بر بردر، لیبل هم رنگ متنش قرمز بشه توی حالت ارور
