### ISSUE TITLE
Sign up UI review

### ISSUE THREAD

**Issue by aligol20** [sirraminyavari/RaaiVanUI#69]
سلام امیرحسین جان
لطفا مجددا نگاه کن و اگر ایرادی بود همین جا برام کامنت بذار

<img width="653" alt="Screen Shot 2021-04-01 at 6 08 56 PM" src="https://user-images.githubusercontent.com/8493249/113303876-bfb7f600-9316-11eb-8cc4-03e1b7b836eb.png">

**Comment by ahs1375** [comment]
- [ ] عنوان صفحه از ثبت نام بشه ایجاد حساب کاربری جدید
- [ ] سایز فونت دکمه دریافت کد تایید با حساب کاربری دارم یکسان نیست
- [ ] ارتفاع دکمه دریافت کد تایید و گوگل هم یکسان نیست
- [ ] اون متن مربوط به قوانین، باید سایز فونتش کوچیکتر بشه و با کد رنگ #BAC9DC باشه.
- [ ] رنگ عنوان صفحه هم با کد رنگ #BAC9DC باشه.

**Comment by aligol20** [comment]
<img width="551" alt="Screen Shot 2021-04-03 at 3 52 19 PM" src="https://user-images.githubusercontent.com/8493249/113477038-945b1580-9494-11eb-9290-9ef0bf862aed.png">
امیرحسین جان لطفا مجددا چک کن
اگر مشکلات رفع شده بودند
لطفا ایشیو رو ببند
@ahs1375
