### ISSUE TITLE
forgot password UI review

### ISSUE THREAD

**Issue by aligol20** [sirraminyavari/RaaiVanUI#70]
<img width="556" alt="Screen Shot 2021-04-01 at 6 15 23 PM" src="https://user-images.githubusercontent.com/8493249/113303981-d6f6e380-9316-11eb-8b5b-f38f3c744e4c.png">

**Comment by ahs1375** [comment]
- [ ] عنوان دکمه ثبت نام به ایجاد حساب کاربری جدید تغییر کنه
- [ ] سایز فونت دکمه ثبت نام با تغییر رمز عبور یکیه ولی با دکمه بازگشت فرق داره

**Comment by aligol20** [comment]
<img width="503" alt="Screen Shot 2021-04-03 at 10 07 37 AM" src="https://user-images.githubusercontent.com/8493249/113469640-6d84eb00-9464-11eb-9e57-6fb0f6073a88.png">
درسته امیرحسین جان اصلاح کردم
@ahs1375
