### ISSUE TITLE
forgot password verification UI review

### ISSUE THREAD

**Issue by aligol20** [sirraminyavari/RaaiVanUI#71]
<img width="887" alt="Screen Shot 2021-04-01 at 6 18 24 PM" src="https://user-images.githubusercontent.com/8493249/113304123-f68e0c00-9316-11eb-95ce-2daba8ab9cea.png">

**Comment by ahs1375** [comment]
- [ ] فضای بالای رمز عبور خود را فراموش کرده ام یه مقدار کمه، مثل بقیه صفحات نیست
- [ ] اون متن بالای اینپوت باید عوض بشه، به نظرم اون قسمت بین دوتا ویرگول برداشته بشه
- [ ] عنوان دکمه هم از تایید تغییر کنه و بشه ورود

**Comment by aligol20** [comment]
<img width="632" alt="Screen Shot 2021-04-03 at 9 00 06 AM" src="https://user-images.githubusercontent.com/8493249/113468368-fe56c900-945a-11eb-8c90-a47f8b44d9bf.png">
امیرحسین جان لطفا تغییرات اعمال شده رو تایید کن
اگر به درستی انجام شده بود
ایشیو رو لطفا ببند
@ahs1375

**Comment by ahs1375** [comment]
فضای بالای صفحات به طور کلی، یعنی عنوان صفحه اگه مثل این صفحه باشه خیلی یکدست تر میشه
https://github.com/sirraminyavari/RaaiVanUI/issues/70
از نظر فاصله و رنگ و سایز فونت

**Comment by aligol20** [comment]
<img width="643" alt="Screen Shot 2021-04-03 at 3 56 12 PM" src="https://user-images.githubusercontent.com/8493249/113477123-1ea37980-9495-11eb-92e8-a694c00e861d.png">

امیرحسین جان لطفا چک کن، به جز اعداد فارسی که سمت بک اند هندل میشه باقی رو اگر مشکلی نبود تایید کن و ایشیو رو ببند
@ahs1375
