### ISSUE TITLE
sign up verification code UI review

### ISSUE THREAD

**Issue by aligol20** [sirraminyavari/RaaiVanUI#72]
<img width="758" alt="Screen Shot 2021-04-01 at 6 18 54 PM" src="https://user-images.githubusercontent.com/8493249/113304200-0a397280-9317-11eb-8f2c-619e16af09a0.png">
<img width="584" alt="Screen Shot 2021-04-01 at 6 23 39 PM" src="https://user-images.githubusercontent.com/8493249/113304543-63a1a180-9317-11eb-8e51-2b4c8c5af7c2.png">

**Comment by ahs1375** [comment]
- [ ] ورودی نامعتبر از سمت راست با اینپوت کد الاین نیست. در یک راستا باشن بهتره

**Comment by aligol20** [comment]
<img width="254" alt="Screen Shot 2021-04-03 at 9 18 36 AM" src="https://user-images.githubusercontent.com/8493249/113468785-935ac180-945d-11eb-9986-3409f936816c.png">
امیرحسین جان تغییرات اعمال شد، لطفا مجددا چک کن اگر همه چیز اوکی بود ایشیو رو لطفا ببند

**Comment by aligol20** [comment]
<img width="526" alt="Screen Shot 2021-04-03 at 3 58 40 PM" src="https://user-images.githubusercontent.com/8493249/113477197-780ba880-9495-11eb-9e95-29a4c41079e3.png">

درسته امیرحسین جان
تصویر قبل مربوط با کد تایید ریست پسورد هستش
اگر اصلاح ها انجام شده و اوکیه
لطفا ایشیو رو ببند
@ahs1375
